---
title: The Physics of Time Loops
description: "\"Do you ever have déjà vu, Mrs. Lancaster?\""
author: Bassel Saleh
date: "2023-02-09"
categories: Explainer
---

## This Feels Familiar

"What was that noise?" I asked myself as I spun wildly around looking for the source of the loud bang. I had just spend the past half hour or so travelling around the solar system in awe, carefully twisting and turning my spaceship to land on exotic planets and bouncing gleefully around them in my jet-powered spacesuit looking for clues. It wasn't long before I located the source of the bang, a massive explosion glowing bright blue, expanding out from where the sun had been moments before. When the powerful blast washed over me and obscured my vision, I thought perhaps it was all over, but moments later I awoke with a sharp breath, staring up at the night sky from the safety of my cozy home planet Timber Hearth. I was standing in exactly the same place I had been at the start of my adventure, the sun still intact and everything else exactly where it had been.

This was the delightful experience of playing the video game [*Outer Wilds*](https://www.mobiusdigitalgames.com/outer-wilds.html) for the first time. After going through the loop several times, I found myself starting each one with a greater sense of urgency, trying my hardest to get to the next location and uncover the next clue before the inevitable supernova would send me back to the start. I became much more efficient at flying my spaceship and hurtling past early obstacles on my path to uncover the secrets of the universe. You see, time loops can be a powerful device for storytelling. For video games in particular, putting the player in the shoes of someone repeating the same experiences over and over again, with the mission to try *something* new to change the loop, creates frustration and exhiliration. It encourages the player to engage with themes like free will and the futility of trying to problem solve when control is repeatedly taken away from you.

Between games like [*Deathloop*](https://bethesda.net/en/game/deathloop), [*Returnal*](https://housemarque.com/games/returnal), and [*12 Minutes*](https://twelveminutesgame.com/), time loops appear to be a popular mechanic in video games recently. Of course, the concept of a time loop is significantly older and more medium-cutting than the current video game boom, from classic films like [*Groundhog Day*](https://www.imdb.com/title/tt0107048/) and [*Edge of Tomorrow*](https://www.imdb.com/title/tt1631867/) to the 1915 Russian novel [*Strange Life of Ivan Osokin*](https://en.wikipedia.org/wiki/Strange_Life_of_Ivan_Osokin). My experience with *Outer Wilds* in particular got me thinking about what the rules are in this universe that would allow such a story to be logically consistent. And how different do these rules need to be from the laws of physics governing *our* universe, the real one that we all live in. Do the laws of physics allow for time loops to plausibly exist? If not, in what ways would the laws need to be modified to permit them? Is there a way of formulating physical laws, even in principle, that *could* permit time loops without disintegrating into a pile of paradoxes and contradictions?

Of course, if you want to be a bit glib, you could argue that this whole avenue of thinking is silly. These are fictional stories after all, so who cares about the minutia of physics in analyzing them. The thing is, I kind of agree. Science fiction stories can be wonderful and enjoyable even when their physical worlds bear no resemblance to the one we live in. But I happen to also believe that the interplay between true science and science fiction is both fascinating and useful, for finding new interesting stories to tell as well as finding new scientific avenues to pursue. So for now we will proceed under the assumption that asking such questions might lead us to interesting places, and let our imaginations do the rest.

## The Red Herring of Closed Timelike Curves

I looked up "the physics of time loops" and found lots of popular science articles on the subject, including [one that interviewed one of the game designers of *Deathloop*](https://next.voxcreative.com/ad/22676555/time-loop-science-deathloop-video-game). While several of these articles were quite engaging to read, I was a bit disappointed to find little more than a cursory reference to some physics here and there, rather than a detailed discussion of how these physical theories would best explain time loops. Many articles jumped right to talking about *closed timelike curves* (CTCs), which are a mathematical feature of some very specific solutions to Einstein's equations for [general relativity](https://en.wikipedia.org/wiki/Introduction_to_general_relativity#:~:text=General%20relativity%20is%20a%20theory,from%20their%20warping%20of%20spacetime.). In the somewhat broader discussion of more general time travel in science fiction, CTCs come up a lot, as they allow for a relatively straightforward way to allow one to travel to the past. More precisely, a CTC is a path in curved spacetime, such that if you hopped in a spaceship and travelled along it, you would end up back when you started. This isn't through some magical teleportation or traversal backward in time, it's simply a quirky consequence of extremely curved spacetimes, some of which are technically allowed in general relativity.

There are issues with taking CTCs too seriously, and some of my thoughts on this were informed by [Sean Carroll's excellent podcast episode about time travel](https://www.preposterousuniverse.com/podcast/2020/11/23/124-solo-how-time-travel-could-and-should-work/), where he investigates in detail what some of these issues are. But for time loops specifically, pointing the discussion toward CTCs is misleading for many reasons. Most blatantly, CTCs exist mathematically as part of what Carroll calls a "single consistent universe". If you were to use a CTC to travel backward in time, you would not find that events are any different than the last time you went through them. There are not alternate versions of events that you're free to pick between each time you experience the loop, there is just *the* one universe, one sequence of concrete events, that you happen to traverse over and over again. This is just completely at odds with the kind of time travel that exists in time loop stories. In the latter, it seems more like time is something that can be unwound, events "undoing" themselves or otherwise resetting, such that choices you make this time induce slightly different initial conditions that can propagate into wildly different outcomes. For this to work, the player/protagonist must exist *outside* of the time-unwinding mechanism, or else all their memories would also be unwound and the decisions they make would be exactly the same.

Other small issues with the CTC picture exist as it relates to time loops. For one thing, if a time loop is to be the result of traversing a CTC, it doesn't seem logically possible for it to depend in some way on the experience of the character. It's a lot easier to make sense of a loop if it exists for a fixed period of time. Some time loops seem to be of variable length, such as in *Groundhog Day* and *Palm Springs*, where characters only reset the loop when they fall asleep or die. Many video game loops are similar, where some unpredictable event (like death) can trigger the loop. *Outer Wilds*, even though it has this death = loop property, actually does pretty well at avoiding the issue, since the sun goes supernova after some fixed, constant amount of time no matter what. With this property, the loop seems less attached to the conscious experience of the protagonist. You could imagine for example that if the protagonist dies, the rest of the universe chugs along until the sun explodes once more, and only then does the protagonist get sent back to the start of the loop and regain consciousness.

There's also a pretty solid consensus that CTCs, despite being theoretically allowed by the equations of general relativity, are practically impossible to ever create in the universe, either because of the need for negative mass, or infinite mass, or other exotic features like cosmic strings and wormholes. But we don't even need to defer to these issues to dismiss CTCs as being relevant for time loop stories. They just don't produce the desired narrative effect.

## Winding Back the Clock

So if the CTCs of general relativity can't explain time loops, is there anything in physics that can? I mentioned the time unwinding idea, but that is sort of vague and magical. Real macroscopic events in the universe are *not* time reversible, due to the second law of thermodynamics. Ok so fine, as artists trying to craft an interesting narrative, what ideas can we lean on to at least be consistent? In principle, due to the time reversal symmetry of the *fundamental* laws of physics, if we had some way of going through every particle in the universe and pointing their momenta in the exact opposite direction, we could press play again and watch everything perfectly undo itself. Then of course once a desired state is reached (the start of the loop), we would need to pause and go flip all the momenta again so that events could go forward from there. Unfortunately, we have to somehow exempt the particles that make up the protagonist from this process, at least from their potential death on backward. I suppose we also need to knock them unconscious while all the unwinding is happening, or else they would witness and have memories of everything else going on. So ok fine, at some specified event (the sun exploding, for example), we grab the protagonist, knock them out, isolate them completely from everything else in the universe, go through and flip all the particle momenta so that the past 22 minutes or whatever perfectly unwinds, go through and flip all the momenta again once we hit the start of the loop, then throw the protagonist back into the universe to wake up and wonder how the hell they're reliving the same day.

This seems... at least plausible (in a classical universe anyway), but I can't stress enough just how *immense* a power would be needed to do this. Maybe we don't have to go mess with the *entire* universe, if the solar system is isolated enough and the time interval we're reversing is short enough, but still. This takes a nearly [Laplace's demon](https://en.wikipedia.org/wiki/Laplace%27s_demon) level of knowledge and computing power, not to mention the unfortunate reality that all of the momentum flipping has to happen *at exactly the same time*, which is troubling because the concept of simultaneity is its own confusing can of worms. Still, even if it's practically speaking *stupendously* difficult, this is at least a logically consistent mechanism for the time loop to happen, especially since the intelligence playing Laplace's demon in this example could just take the protagonist to some other solar system while all the resetting happens and then bring them back.

The above scenario gets messier when you acknowledge that the universe isn't actually classical, it's quantum mechanical. It is not possible to go flip all the momenta of all of the particles, because they do not have well-defined momenta at all. Furthermore, in the standard model of particle physics the fundamental laws don't actually have nice, clean time reversal symmetry. They have what is called [CPT invariance](https://en.wikipedia.org/wiki/CPT_symmetry), where the laws only function normally if you reverse time *and* flip the charge of all particles *and* flip the polarity of all particles (swap right and left handedness, so to speak) at the same time. But ok *fine*, you do all that... somehow. The problem is that in quantum mechanics, the observable thermodynamic evolution of the universe is not deterministic, at least not to any one observer. Quantum outcomes will occasionally be random, such that if you hit restart on the universe and watched it unfold from the exact same initial condition as before, you wouldn't necessarily observe the exact same unfolding of events. So either you need to force the quantum measurements to somehow reproduce the same results they had last time (nothing in our understanding of quantum mechanics suggests this is even remotely possible), or you need to prepare yourself to make the final plunge: into the universe of many worlds.

## You Get a World, and You Get a World

If you aren't aware, it turns out there isn't just one theory of quantum mechanics, there are several different competing formulations. These different theories are ontologically distinct, saying different things about what the universe fundamentally is like, but they all agree with each other when predicting the outcomes of experiments. For this reason, some modern physicists disagree that they truly constitute different scientific theories, and there's a whole [philosophical debate on this subject](https://en.wikipedia.org/wiki/Interpretations_of_quantum_mechanics), if you're curious. For our purposes we're going to adopt the so-called [many-worlds formulation of quantum mechanics](https://en.wikipedia.org/wiki/Many-worlds_interpretation), since this is the physical theory which unlocks the pantheon of parallel universes that might save us in our pursuit of time loop physics.

In simple terms, many-worlds posits that there is only one thing that is real, the quantum mechanical wavefunction of the universe, and this wavefunction evolves according to the Schrödinger equation. Quantum mechanical orthodoxy demands that this wavefunction collapse to one discrete outcome when a measurement is made, but in many-worlds, we do away with the concept of collapse and replace it with the concept of *branching*. Whenever a quantum measurement occurs that could have gone one way or another, the universe splits into two, or three, or maybe infinite copies of itself, where each copy proceeds with one of the outcomes. These parallel copies are branches of the wavefunction, and believing in them allows one to keep an internally consistent picture of the world.

This is all perfectly kosher, in the sense that many-worlds (or Everettian) quantum mechanics is a genuine, bonafied physical theory, with equations and everything, one that is consistent with the universe we actually live in. However, before you get excited about jumping around to alternate timelines to meet different versions of yourself, it's worth knowing what *is* and *is not* possible in this theory. For one thing, many worlds says that once a branching of the wavefunction happens, *that's it*. The branches no longer interact or have any causal influence over each other, and there is no way to travel from one to the other.

*But ok fine*, if we *really* want to make time loops happen (and we do, if we are writers trying to tell a story), let's say we can invent some mechanism that lets a person (or spaceship) jump between branches of the wavefunction. Ignoring for the moment any wild paradoxes that might create, can we at least *imagine* that such a thing were possible? If we let ourselves do this, what would such a person's experience be like? Would it feel the way it felt to Bill Murray in *Groundhog Day* or to the spacefaring protagonist of *Outer Wilds*?

## Winding Back the... Quantum Clock?

Well, not quite. There is one more sticking point, which is that if we're jumping between branches, that doesn't let us choose what moment of time we'd like to jump to. Really what we need is to travel *backwards* to a point before the branching. So it turns out we actually need to refer back to our old thermodynamic argument for unwinding events, but this time instead of flipping momenta to reverse time like Laplace's demon, we need our grand intelligence (perhaps called Everett's demon) to unwind the quantum mechanical wavefunction of the universe, which is to say unwind *all of the branches together*, using CPT invariance to ensure it all stays consistent. This effectively undoes the series of quantum entanglements that caused the wavefunction to branch, bringing us back to a point where we can pause, take a breath, and apply the CPT transformation once more to point us back in the right direction. In a very real sense, this is *exponentially harder* than the already insane task of reversing particle momenta in the classical universe, and unlike when we could imagine dragging our unconscious protagonist to a nearby solar system, now we need our protagonist to somehow sit *outside* of the wavefunction of the universe? That doesn't seem plausible at all. But in my opinion it's at least better than pretending quantum mechanics doesn't exist, so it's about as good as we're going to get. So with all that said... *now* can we answer whether this wacky universe would behave like *Groundhog Day*, *Outer Wilds*, *Deathloop*, etc.?

In principle, yes... I think. This is where not being an expert starts to hinder us, because the details of how such a bizarre thing might work are murky and unreliable. At some point, you have to start putting pen to paper and ask yourself what the equations tell you. Scientific theories are not just collections of ideas, they have well-posed mathematical structure, and we better be careful about messing with that structure lest we accidentally break everything else about the universe. But in my humble opinion, considering the discussion we've had so far, this is the version of time looping physics that makes the most sense to me, or at least creates the least amount of trouble. You have to do a lot of hand waving about how one might travel outside of their own branch, and you might have to do some careful tweaking to make sure you don't end up somehow inside of yourself or otherwise conflicting with matter on another branch, but if we suspend a little bit of disbelief, then this is the physical theory that has the most explanatory power for justifying a genuine time loop. It's the only one that lets us make sense of the fact that each loop feels different, with different actions leading to different outcomes. From a story perspective, this ingredient is essential, and you could never get it with closed timelike curves alone.

Sean Carroll claims that the "right" way to do time travel in science fiction is with the single, consistent universe idea. Which is to say, no matter what kind of time-faring shenanigans you get up to, whether it's CTCs or something else, you'll never exert causal influence in a way that makes things happen any differently than they already happened. This is in some sense the most physics-pleasing way of doing time travel, but unfortunately, with time loop stories this explanation was dead from the word go. That is what sent me on this rabbit hole of trying to find the next best explanation. But please, if you have some idea that you think works even better, or if you find a flaw in the arguments I've given here, let me know! I can always be reached on Twitter [@mrbassoule](https://twitter.com/mrbassoule).